apiVersion: v1
kind: Service
metadata:
  name: postgres-db # Nombre DNS que usarán otros servicios para conectar
spec:
  selector:
    app: postgres-db # Selecciona los Pods con esta etiqueta (del Deployment)
  ports:
    - protocol: TCP
      port: 5432       # Puerto por el que otros servicios acceden
      targetPort: 5432 # Puerto en el contenedor Postgres
  type: ClusterIP # Solo accesible dentro del clúster