apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret # Nombre del Secret
type: Opaque
data:
  # Clave que usaremos en la variable de entorno del Deployment de Postgres
  # Valor es la contraseña ('password' del docker-compose) codificada en Base64
  POSTGRES_PASSWORD: cGFzc3dvcmQ= # <--- Reemplaza esto con tu contraseña real codificada en Base64