apiVersion: v1
kind: Service
metadata:
  name: users-service # Nombre DNS para este servicio
spec:
  selector:
    app: users-service # Selecciona los Pods del Deployment de usuarios
  ports:
    - protocol: TCP
      port: 8000       # Puerto expuesto por el Service
      targetPort: 8000 # Puerto en los Pods
  type: ClusterIP